---
- hosts: localhost
  connection: local
  vars:
    ssh_key: coreos
    k8s_version: 1.5.2
    k8s_num_nodes: 2
    k8s_security_group_name: k8s
    k8s_node_prefix: coreos
    k8s_username: foobar
    k8s_password: FdKPSuwQ
# This template name is specific to http://exoscale.ch, replace it
    k8s_template: CoreOS
    k8s_instance_type: CO-CoreOS

    k8s_binaries: https://storage.googleapis.com/kubernetes-release/release/v{{ k8s_version }}/bin

  roles:
    - common
    - k8s
